name: Build Avalon-Micro
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    if: ${{ inputs.perform_deploy }}
    steps:
      - uses: actions/setup-go@v4.0.0
      - uses: actions/checkout@v3.5.2
      - uses: extractions/setup-just@v1
      - name: Show GO env
        run: |
          go env -w GOARCH=${{ matrix.arch }}
          go env
      - name: Windows - Setting up just
        if: matrix.platform == 'windows-latest'
        run: |
          set shell := ["powershell.exe", "-c"]
      - name: Get Files
        run: |
          git clone ${{ secrets.AVALON_MICRO_GIT_REPO_SECRET }} -c http.extraheader="${{ secrets.AVALON_MICRO_GIT_REPO_AUTH_SECRET }}"
          git checkout -b ${{ inputs.branch }}
      - name: Build Avalon Micro
        run: |
          cd ./Avalon-Micro
          just os=${{ matrix.platform }} arch=${{ matrix.arch }}
      - name: Create Artifact
        run: |
          tar -cvf Avalon-Micro-${{ matrix.platform }}-${{ matrix.arch }}.tar ./Avalon-Micro/bin
      - name: Upload to file repository
        run: |
          curl -H "${{ secrets.AVALON_MICRO_FILE_REPO_AUTH_SECRET }}" ${{ secrets.AVALON_MICRO_FILE_REPO_SECRET }} --upload-file Avalon-Micro-${{ matrix.platform }}-${{ matrix.arch }}.tar

      
