name: Build Avalon-Micro
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v4.0.0
      - uses: actions/checkout@v3.5.2
        with:
          repository: cute-rui/Avalon-Micro
          token: ${{ secrets.AVALON_MICRO_GIT_REPO_AUTH_SECRET }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: extractions/setup-just@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Show GO env
        run: |
          go env -w GOARCH=${{ matrix.arch }}
          go env -w CGO_ENABLED=0
          go env
      - name: Windows - Setting up just
        if: matrix.platform == 'windows-latest'
        run: |
          set shell := ["powershell.exe", "-c"]
      - name: Build Avalon Micro
        run: |
          just os=${{ matrix.platform }} arch=${{ matrix.arch }}
          cp ./justfile ./bin
      - name: Create Artifact
        run: |
          tar -czvf Avalon-Micro-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz ./bin
      - name: Upload to file repository
        run: |
          curl -H "${{ secrets.AVALON_MICRO_FILE_REPO_AUTH_SECRET }}" ${{ secrets.AVALON_MICRO_FILE_REPO_SECRET }} -F file=@"Avalon-Micro-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz"

      
