name: Clean
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Avalon-Micro]
    types: [completed]
  

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:
        - name: Delete all containers from repository without tags
          uses: Chizkiyahu/delete-untagged-ghcr-action@v6
          with:
            token: ${{ secrets.CLEANER_TOKEN }}
            repository_owner: ${{ github.repository_owner }}
            untagged_only: true
            owner_type: user # or user
