name: test
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Upload to file repository
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"view":"https://github.com/TUT-LIFRMer/rules","name":"something","type":"document"}' "https://www.feishu.cn/flow/api/trigger-webhook/fc4e11a48201b5be818bbd6a9960a3c4"
      
